# Please don't use ADO UI defined scheduled triggers because it takes precedence over YAML scheduled triggers.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers
trigger: none
pr: pr

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build'

- task: PowerShell@2
  displayName: 'Install Pester'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester'
    pwsh: true

- task: PowerShell@2
  displayName: 'Test'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester'
    pwsh: true
